name: Run Scrapers and Update Data

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:         # allows manual triggering in the Actions tab

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional if playwright is used:
          playwright install --with-deps

      - name: Run scraping scripts
        run: |
          python supersport_scraper.py
          python sunbet_scraper.py
          python betjets_scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update scraped data" || echo "No changes to commit"
          git push
